### ISSUE TITLE
Add pool information to the lake model

### ISSUE THREAD

**Issue by silveryfu** [digi-project/digi#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by runey333** [comment]
A preliminary design: (WIP)
We can start by implementing aggregate statistics (Number of Pools, Total Size of Pools, Average Pool Size).
We can start by adding the following to lake's model.yaml
`agg_stats:
    num_pools: number
    total_pool_size: number
    ave_pool_size: number
`
There will be 2 ways we update pool information: event driven and polling
Event Driven:
We can use the /events endpoint [here](https://zed.brimdata.io/docs/lake/api#events) to subscribe to an event stream, and update pool count and pools keys on "pool-new" events. The motivation is that pools are created relatively infrequently.

Polling:
We can set up a thread that runs a function on a schedule. This function will update sizes of each pool (how TBD), as well as the aggregate size. The motivation here is that records are added/removed often, so size changes often and is best recorded via polling.

**Comment by silveryfu** [comment]
@runey333:
* It will help to breakdown and update your doc on what the lake driver will do after you see an event (e.g. how to obtain # of pools etc.)
* For polling, just having a timed thread that query the Zed lake periodically should do.

re. Race condition: per our earlier discussion, let's assume the eventful updates and polling updates will maintain different statistics; and with patch_spec, they will not overwrite each other.

These aside, the design looks fine to me but others feel free to chime in and comment below.
