### ISSUE TITLE
Allow digi driver to CRUD non-default models 

### ISSUE THREAD

**Issue by silveryfu** [digi-project/digi#37]
The digi driver should be able to watch/create/patch/delete models besides the default one.

**Support Watch** 
Developers can specify the `kind` the digi will watch for. 
> In the digi model, include an attribute `watch`.

**Patch** 
The `patch_spec` in `digi.util` should work as before. The access associated with the service account may need to be rewired.

**Create and delete** 
The digi driver can create new models and delete the ones created by it. 

To create a model:
* The CRD for the model should exist, otherwise report error.
* The `digi.util` should include a `create_model` method.
* Once the model is created, the driver automatically start watching it.

To delete a model:
* The `digi.util` should include a `delete_model` method.

The digi should manage the lifecycle of any models it creates. If the digi is removed, all the models it creates should die with it. We should leverage the ownership ref feature on apiserver to enable auto-removal of models.

**Comment by TarasPriadka** [comment]
What exactly is a default model? Is it just the model of the digi which runs the driver?
