### ISSUE TITLE
Move Matter port access to "-d"

### ISSUE THREAD

**Issue by PotatoParser** [digi-project/digi#43]
**Is your feature request related to a problem? Please describe.**
Currently Matter ports are exposed by default. This could pose a security risk.

**Describe the solution you'd like**
Ports should be opened dependent on digilite configurations.

**Describe alternatives you've considered**

**Additional context**
N/A

**Comment by silveryfu** [comment]
To clarify, this is in the `driver/deploy/template/actor.yaml`.
